import Link from "next/link";
import { listEnrollmentReports } from "@/lib/training/courses";
import { requireTrainingStaff } from "@/lib/training/auth";

export default async function AdminReportsPage() {
  await requireTrainingStaff();
  const rows = await listEnrollmentReports();
  return <main className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><Link href="/admin" className="text-sm font-medium text-[#007c8b]">← Administration</Link><div className="mt-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#007c8b]">Reporting</p><h1 className="mt-3 text-5xl font-semibold tracking-tight text-[#002f65]">Enrollment report</h1><p className="mt-4 text-[#526b78]">Assignments and completion records from the training platform.</p></div><a href="/admin/reports/export" className="rounded-xl bg-[#002f65] px-5 py-3 text-sm font-semibold text-white">Download CSV</a></div><div className="mt-10 overflow-x-auto rounded-2xl bg-white ring-1 ring-[#d5e9ed]"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#d5e9ed] text-[#526b78]"><tr><th className="px-5 py-4 font-medium">Learner</th><th className="px-5 py-4 font-medium">Course</th><th className="px-5 py-4 font-medium">Status</th><th className="px-5 py-4 font-medium">Assigned</th><th className="px-5 py-4 font-medium">Expires</th><th className="px-5 py-4 font-medium">Completed</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-[#edf4f5] last:border-0"><td className="px-5 py-4 font-medium text-[#002f65]">{row.learner_name}</td><td className="px-5 py-4 text-[#526b78]">{row.course_title}</td><td className="px-5 py-4 text-[#526b78]">{row.status}</td><td className="px-5 py-4 text-[#526b78]">{new Date(row.assigned_at).toLocaleDateString()}</td><td className="px-5 py-4 text-[#526b78]">{row.expires_at ? new Date(row.expires_at).toLocaleDateString() : "—"}</td><td className="px-5 py-4 text-[#526b78]">{row.completed_at ? new Date(row.completed_at).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-10 text-center text-sm text-[#526b78]">No enrollment records yet.</p>}</div></main>;
}
