"use client";

import { useMemo, useState } from "react";

type ReportRow = { id: string; learner_name: string; course_title: string; lessons_completed: number; lessons_total: number; progress_percentage: number; latest_score: number | null; latest_passed: boolean | null; certificate_issued_at: string | null; expires_at: string | null; days_until_expiry: number | null; at_risk: boolean };

export default function ProgressReportTable({ rows }: { rows: ReportRow[] }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const filteredRows = useMemo(() => rows.filter((row) => {
    const matchesQuery = `${row.learner_name} ${row.course_title}`.toLowerCase().includes(query.toLowerCase());
    const matchesStatus = status === "all" || (status === "at-risk" && row.at_risk) || (status === "complete" && row.progress_percentage === 100) || (status === "in-progress" && row.progress_percentage > 0 && row.progress_percentage < 100) || (status === "not-started" && row.progress_percentage === 0);
    return matchesQuery && matchesStatus;
  }), [query, rows, status]);
  return <><div className="mt-8 flex flex-col gap-3 rounded-2xl bg-white p-4 ring-1 ring-[#d5e9ed] md:flex-row"><label className="flex-1"><span className="sr-only">Search learners or courses</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search learners or courses" className="w-full rounded-xl border border-[#d5e9ed] px-4 py-3 text-sm outline-none focus:border-[#007c8b]" /></label><label><span className="sr-only">Filter progress</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="w-full rounded-xl border border-[#d5e9ed] bg-white px-4 py-3 text-sm text-[#526b78] outline-none focus:border-[#007c8b] md:min-w-48"><option value="all">All progress</option><option value="at-risk">At risk</option><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="complete">Complete</option></select></label></div><div className="mt-5 overflow-x-auto rounded-2xl bg-white ring-1 ring-[#d5e9ed]"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#d5e9ed] text-[#526b78]"><tr>{["Learner", "Course", "Progress", "Deadline", "Latest score", "Assessment", "Certificate"].map((heading) => <th key={heading} className="px-5 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id} className="border-b border-[#edf4f5] last:border-0"><td className="px-5 py-4 font-medium text-[#002f65]">{row.learner_name}</td><td className="px-5 py-4 text-[#526b78]">{row.course_title}</td><td className="px-5 py-4 text-[#526b78]">{row.lessons_completed}/{row.lessons_total} ({row.progress_percentage}%)</td><td className={`px-5 py-4 ${row.at_risk ? "font-semibold text-[#b45309]" : "text-[#526b78]"}`}>{row.days_until_expiry === null ? "No deadline" : row.days_until_expiry < 0 ? "Expired" : `${row.days_until_expiry} days left`}</td><td className="px-5 py-4 text-[#526b78]">{row.latest_score === null ? "—" : `${row.latest_score}%`}</td><td className="px-5 py-4 text-[#526b78]">{row.latest_passed === null ? "Not attempted" : row.latest_passed ? "Passed" : "Not passed"}</td><td className="px-5 py-4 text-[#526b78]">{row.certificate_issued_at ? new Date(row.certificate_issued_at).toLocaleDateString() : "—"}</td></tr>)}</tbody></table>{filteredRows.length === 0 && <p className="p-10 text-center text-sm text-[#526b78]">No learner records match these filters.</p>}</div></>;
}
